export const ADD_EXPENSES_LOADER = "ADD_EXPENSES_LOADER";
export const ADD_EXPENSES_SUCCESS = "ADD_EXPENSES_SUCCESS";
export const ADD_EXPENSES_FAILURE = "ADD_EXPENSES_FAILURE";

export const ADD_INCOME_LOADER = "ADD_INCOME_LOADER";
export const ADD_INCOME_SUCCESS = "ADD_INCOME_SUCCESS";
export const ADD_INCOME_FAILURE = "ADD_INCOME_FAILURE";

export const ADD_DELETE_DATA = "ADD_DELETE_DATA";
export const ADD_SEARCH_DATA = "ADD_SEARCH_DATA";



